import ProjectDescription

let workspace = Workspace(
    name: "Metronome",
    projects: [
        "MetronomeApp",
        "MetronomeEngine",
    ],
    generationOptions: .options(
        autogeneratedWorkspaceSchemes: .enabled(codeCoverageMode: .all)
    )
)
